- name: Ensure git and config directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/git"
    - "{{ ansible_env.HOME }}/.config"

- name: Clone the dotfiles repository
  git:
    repo: "https://github.com/rrstickney/dotfiles"
    dest: "{{ ansible_env.HOME }}/git/dotfiles"
    single_branch: yes
    version: main

- name: Symlink the CLI dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - {
        src: "{{ ansible_env.HOME }}/git/dotfiles/bashrc/bash_aliases",
        dest: "{{ ansible_env.HOME }}/.bash_aliases",
      }
    - {
        src: "{{ ansible_env.HOME }}/git/dotfiles/bashrc/bash_exports",
        dest: "{{ ansible_env.HOME }}/.bash_exports",
      }
    - {
        src: "{{ ansible_env.HOME }}/git/dotfiles/bashrc/bashrc",
        dest: "{{ ansible_env.HOME }}/.bashrc",
      }
    - {
        src: "{{ ansible_env.HOME }}/git/dotfiles/starship/starship.toml",
        dest: "{{ ansible_env.HOME }}/.config/starship.toml",
      }
    - {
        src: "{{ ansible_env.HOME }}/git/dotfiles/vim",
        dest: "{{ ansible_env.HOME }}/.config/vim",
      }
