---
- name: install the basics to get things going
  hosts: localhost
  become: true
  pre_tasks:
    - name: update apt cache
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: install some packages
      package:
        name:
          - unzip
          - net-tools
          - vim
          - python3-pip
        state: present

    - name: install some pips
      pip:
        name:
          - github3.py
